name: Deploy Site to AWS

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy CAM stack to production'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Testing
      run: echo '${{ secrets.S3_BUCKET_NAME }} ${{ env.S3_BUCKET_NAME }}'
        
    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude '.git/*' --exclude '.vscode/*'
      
    - name: Invalidate CloudFront cache
      run: export AWS_PAGER=""; aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths '/*'
